#url: http://127.0.0.1:4000/
baseurl: 
username: tomasparks
repo: Dynix-theme-jekyll
<<<<<<< HEAD
branch: master
=======
branch: bootstrap
>>>>>>> bootstrap

# Jekyll source / destination
source: .
destination: _site
